parameters:
    security.exception_listener.class: 'Akeneo\Platform\Bundle\UIBundle\EventListener\ExceptionListener'

services:
    pim_enrich.imagine.loader.flysystem:
        class: 'Akeneo\Platform\Bundle\UIBundle\Imagine\FlysystemLoader'
        arguments:
            - '@akeneo_file_storage.file_storage.filesystem_provider'
            - ['catalogStorage']
        tags:
            - { name: liip_imagine.binary.loader, loader: flysystem_data_loader }

    pim_enrich.resolver.locale:
        class: 'Akeneo\Platform\Bundle\UIBundle\Resolver\LocaleResolver'
        arguments:
            - '@request_stack'
            - '%locale%'

    pim_enrich.version_strategy:
        class: 'Akeneo\Platform\Bundle\UIBundle\VersionStrategy\CacheBusterVersionStrategy'
        arguments:
            - '@pim_catalog.version_provider'
