services:
    pim_enrich.factory.mass_edit_notification:
        class: 'Akeneo\Platform\Bundle\ImportExportBundle\Factory\MassEditNotificationFactory'
        arguments:
            - ['quick_export', 'mass_edit', 'mass_delete']
            - '%pim_notification.entity.notification.class%'
        tags:
            - { name: pim_notification.factory.notification }
