assetic:
    bundles:
        - OroAsseticBundle
        - PimUserBundle
        - PimUIBundle
        - AkeneoChannelBundle
        - AkeneoPimEnrichmentBundle
        - AkeneoPimStructureBundle
        - PimEnrichBundle
        - PimNotificationBundle
    filters:
        lessphp:
            file: '%kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php'
            apply_to: \.less$
