services:
    # Form
    pim_enrich.form.family:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_family_form'
            - 'Akeneo\Pim\Structure\Bundle\Form\Type\FamilyType'

    pim_enrich.form.currency:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_currency_form'
            - 'Akeneo\Platform\Bundle\UIBundle\Form\Type\CurrencyType'

    pim_enrich.form.group:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_group_form'
            - 'Akeneo\Pim\Enrichment\Bundle\Form\Type\GroupType'

    pim_enrich.form.group_type:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_grouptype_form'
            - 'Akeneo\Pim\Structure\Bundle\Form\Type\GroupTypeType'

    pim_enrich.form.association_type:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_associationtype_form'
            - 'Akeneo\Pim\Structure\Bundle\Form\Type\AssociationTypeType'

    pim_enrich.form.type.async_select:
        class: Akeneo\Platform\Bundle\UIBundle\Form\Type\AsyncSelectType
        arguments:
            - '@router'
            - '@pim_enrich.factory.transformer.identifiable_model'
        tags:
            - { name: form.type, alias: pim_async_select }
