services:
    # Form
    pim_enrich.form.family:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_family_form'
            - 'Akeneo\Pim\Structure\Bundle\Form\Type\FamilyType'

    pim_enrich.form.currency:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_currency_form'
            - 'Akeneo\Platform\Bundle\UIBundle\Form\Type\CurrencyType'

    pim_enrich.form.group:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_group_form'
            - 'Akeneo\Pim\Enrichment\Bundle\Form\Type\GroupType'

    pim_enrich.form.group_type:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_grouptype_form'
            - 'Akeneo\Pim\Structure\Bundle\Form\Type\GroupTypeType'

    pim_enrich.form.association_type:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_associationtype_form'
            - 'Akeneo\Pim\Structure\Bundle\Form\Type\AssociationTypeType'

    pim_enrich.form.type.async_select:
        class: Akeneo\Platform\Bundle\UIBundle\Form\Type\AsyncSelectType
        arguments:
            - '@router'
            - '@pim_enrich.factory.transformer.identifiable_model'
        tags:
            - { name: form.type, alias: pim_async_select }


parameters:
    pim_enrich.form.type.group.class:            Pim\Bundle\EnrichBundle\Form\Type\GroupType
    pim_enrich.form.type.category.class:         Pim\Bundle\EnrichBundle\Form\Type\CategoryType
    pim_enrich.form.type.association.class:      Pim\Bundle\EnrichBundle\Form\Type\AssociationType
    pim_enrich.form.type.association_type.class: Pim\Bundle\EnrichBundle\Form\Type\AssociationTypeType
    pim_enrich.form.type.media.class:            Pim\Bundle\EnrichBundle\Form\Type\MediaType

    pim_enrich.form.type.available_attributes.class:                Pim\Bundle\EnrichBundle\Form\Type\AvailableAttributesType
    pim_enrich.form.type.localized_collection.class:                Pim\Bundle\EnrichBundle\Form\Type\LocalizedCollectionType

    pim_enrich.form.type.light_entity.class: Pim\Bundle\EnrichBundle\Form\Type\LightEntityType

    pim_enrich.form.type.object_identifier.class: Pim\Bundle\EnrichBundle\Form\Type\ObjectIdentifierType

    pim_enrich.form.type.translatable_field.class:         Pim\Bundle\EnrichBundle\Form\Type\TranslatableFieldType

    pim_enrich.type.entity_identifier.class: Pim\Bundle\EnrichBundle\Form\Type\EntityIdentifierType
