parameters:
    pim_enrich.form.handler.group.class: Akeneo\Pim\Enrichment\Bundle\Form\Handler\GroupHandler

services:
    pim_enrich.form.handler.group:
        class: '%pim_enrich.form.handler.group.class%'
        arguments:
            - '@pim_enrich.form.group'
            - '@request_stack'
            - '@pim_catalog.saver.group'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.localization.localizer.converter'



