parameters:
    pim_enrich.provider.structure_version.class:   Akeneo\Pim\Enrichment\Bundle\StructureVersion\Provider\StructureVersion

services:
    # Structure version provider
    pim_enrich.provider.structure_version.product:
        class: '%pim_enrich.provider.structure_version.class%'
        deprecated: 'The "%service_id%" service is deprecated. Use "pim_structure_version.provider.structure_version.product" instead'
        arguments:
            - '@doctrine'
        calls:
            - [addResource, ['%pim_catalog.entity.association_type.class%']]
            - [addResource, ['%pim_catalog.entity.attribute.class%']]
            - [addResource, ['%pim_catalog.entity.attribute_group.class%']]
            - [addResource, ['%pim_catalog.entity.category.class%']]
            - [addResource, ['%pim_catalog.entity.channel.class%']]
            - [addResource, ['%pim_catalog.entity.family.class%']]
            - [addResource, ['%pim_catalog.entity.group.class%']]
            - [addResource, ['%pim_catalog.entity.locale.class%']]

    pim_enrich.provider.structure_version.group:
        class: '%pim_enrich.provider.structure_version.class%'
        deprecated: 'The "%service_id%" service is deprecated. Use "pim_structure_version.provider.structure_version.group" instead'
        arguments:
            - '@doctrine'
        calls:
            - [addResource, ['%pim_catalog.entity.attribute.class%']]
            - [addResource, ['%pim_catalog.entity.attribute_group.class%']]
            - [addResource, ['%pim_catalog.entity.channel.class%']]
            - [addResource, ['%pim_catalog.entity.locale.class%']]

    pim_enrich.provider.structure_version.group_type:
        class: '%pim_enrich.provider.structure_version.class%'
        deprecated: 'The "%service_id%" service is deprecated. Use "pim_structure_version.provider.structure_version.group_type" instead'
        arguments:
            - '@doctrine'
        calls:
            - [addResource, ['%pim_catalog.entity.locale.class%']]

    pim_enrich.provider.structure_version.attribute:
        class: '%pim_enrich.provider.structure_version.class%'
        deprecated: 'The "%service_id%" service is deprecated. Use "pim_structure_version.provider.structure_version.attribute" instead'
        arguments:
            - '@doctrine'
        calls:
            - [addResource, ['%pim_catalog.entity.attribute_group.class%']]
            - [addResource, ['%pim_catalog.entity.locale.class%']]

    pim_enrich.provider.structure_version.family_variant:
        class: '%pim_enrich.provider.structure_version.class%'
        deprecated: 'The "%service_id%" service is deprecated. Use "pim_structure_version.provider.structure_version.family_variant" instead'
        arguments:
            - '@doctrine'
        calls:
            - [addResource, ['%pim_catalog.entity.attribute.class%']]
            - [addResource, ['%pim_catalog.entity.family.class%']]
            - [addResource, ['%pim_catalog.entity.locale.class%']]
