parameters:
    pim_enrich.reader.database.filtered_product_and_product_model.class: Akeneo\Pim\Enrichment\Component\Product\Connector\Reader\Database\MassEdit\FilteredProductAndProductModelReader
    pim_enrich.reader.database.product_and_product_model.class: Akeneo\Pim\Enrichment\Component\Product\Connector\Reader\Database\MassEdit\ProductAndProductModelReader
    pim_enrich.reader.database.filtered_product_reader.class: Akeneo\Pim\Enrichment\Component\Product\Connector\Reader\Database\MassEdit\FilteredProductReader
    pim_enrich.reader.database.filtered_product_model_reader.class: Akeneo\Pim\Enrichment\Component\Product\Connector\Reader\Database\MassEdit\FilteredProductModelReader

services:
    pim_enrich.reader.database.filtered_product_and_product_model:
        class: '%pim_enrich.reader.database.filtered_product_and_product_model.class%'
        arguments:
            - '@pim_catalog.query.product_and_product_model_query_builder_factory'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.manager.completeness'
            - '@pim_catalog.converter.metric'
            - true
            - false

    pim_enrich.reader.database.product_and_product_model:
        class: '%pim_enrich.reader.database.product_and_product_model.class%'
        arguments:
            - '@pim_catalog.query.product_and_product_model_query_builder_factory'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.manager.completeness'
            - true

    pim_enrich.reader.database.grouped_product_and_product_model:
        class: '%pim_enrich.reader.database.product_and_product_model.class%'
        arguments:
            - '@pim_catalog.query.product_and_product_model_query_builder_factory'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.manager.completeness'
            - false

    pim_enrich.reader.database.products_and_variant_products_of_product_models:
        class: '%pim_enrich.reader.database.filtered_product_and_product_model.class%'
        arguments:
            - '@pim_catalog.query.product_and_product_model_query_builder_factory'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.manager.completeness'
            - '@pim_catalog.converter.metric'
            - true
            - true

    pim_enrich.reader.database.product:
        class: '%pim_enrich.reader.database.filtered_product_reader.class%'
        arguments:
            - '@pim_catalog.query.product_and_product_model_query_builder_factory'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.manager.completeness'
            - '@pim_catalog.converter.metric'
            - true

    pim_enrich.reader.database.product_model:
        class: '%pim_enrich.reader.database.filtered_product_model_reader.class%'
        arguments:
            - '@pim_catalog.query.product_and_product_model_query_builder_factory'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.converter.metric'
