catalog_volume:
    resource: '@PimEnrichBundle/Resources/config/routing/catalog_volume.yml'
    prefix: /catalog-volumes

product:
    resource: '@PimEnrichBundle/Resources/config/routing/product.yml'
    prefix: /enrich/product

product_grid_filter:
    resource: '@PimEnrichBundle/Resources/config/routing/product_grid_filter.yml'
    prefix: /enrich/product-grid-filter

mass_edit_action:
    resource: '@PimEnrichBundle/Resources/config/routing/mass_edit_action.yml'
    prefix: /enrich/mass-edit-action

group:
    resource: '@PimEnrichBundle/Resources/config/routing/group.yml'
    prefix: /enrich/group

grouptype:
    resource: '@PimEnrichBundle/Resources/config/routing/grouptype.yml'
    prefix: /configuration/group-type

measures:
    resource: '@PimEnrichBundle/Resources/config/routing/measures.yml'
    prefix: /configuration/measures


