parameters:
    pim_enrich.twig.object_class_extension.class: Pim\Bundle\EnrichBundle\Twig\ObjectClassExtension
    pim_enrich.twig.translations_extension.class: Pim\Bundle\EnrichBundle\Twig\TranslationsExtension

services:
    # Twig extensions
    pim_enrich.twig.object_class_extension:
        class: '%pim_enrich.twig.object_class_extension.class%'
        tags:
            - { name: twig.extension }

    pim_enrich.twig.translations_extension:
        class: '%pim_enrich.twig.translations_extension.class%'
        arguments:
            - '@pim_catalog.command_launcher'
            - '@request_stack'
            - '%assetic.write_to%'
        tags:
            - { name: twig.extension }
