parameters:
    pim_enrich.twig.object_class_extension.class: Pim\Bundle\EnrichBundle\Twig\ObjectClassExtension

services:
    # Twig extensions
    pim_enrich.twig.object_class_extension:
        class: '%pim_enrich.twig.object_class_extension.class%'
        tags:
            - { name: twig.extension }
