services:
    pim_enrich.twig.category_extension:
        class: 'Akeneo\Pim\Enrichment\Bundle\Twig\CategoryExtension'
        arguments:
            - '@pim_enrich.doctrine.counter.category_registry'
            - '%pim_enrich_max_products_category_removal%'
        tags:
            - { name: twig.extension }
